### ISSUE TITLE
Does ksuid support for Postgres

### ISSUE THREAD

**Issue by tranhoangvuit** [segmentio/ksuid#23]
I'm very exciting about ksuid. But when I want create a new table on postgres with primary key is ksuid. So what kind of data type should I set for ksuid ? How about performance of it in big query ?
Beause with UUID, it's supported by data type is uuid.
Thank you so much

**Comment by achille-roussel** [comment]
You can use char(27) since the textual representation has a fixed length of 27 characters.

If you want to store the KSUID in binary form you may use the bytea data type as well. 

Postgres doesn’t have a custom data type to support KSUIDs.

**Comment by azr** [comment]
Question here, what are the main differences between using char(27) vs bytea ? In terms of performances ? (I'm also good with blog posts). Do you have "prod feedback" ?

**Comment by jgod** [comment]
@azr What conclusion did you come to?

**Comment by achille-roussel** [comment]
`char(27)` will allow you to use the base62 representation of KSUID across systems, otherwise if you use the binary representation in the database you make some operations a lot more complex (e.g. copy/paste values, writing SQL queries, etc...).

I doubt you'll see a measurable difference between either data types, optimizing to facilitate development by using the textual representation seems like the right default; as usual, there may be exceptions, measure in your own use cases if you have any concerns 👍

**Comment by benjamin-kirkbride** [comment]
Also see: https://github.com/VADOSWARE/pg_idkit
