### ISSUE TITLE
KSUID is not nanosecond-aware

### ISSUE THREAD

**Issue by loganintech** [segmentio/ksuid#48]
The [go source code](https://github.com/golang/go/blob/8cfa01943a7f43493543efba81996221bb0f27f8/src/time/time.go#L139) shows that a wall time for `time.Time` is in fact 8 bytes, a uint64. Unlike how it's defined [in this library](https://github.com/segmentio/ksuid/blob/bf376a7b4736ea36be30d70e72e4420d607bd532/ksuid.go#L22) to be 4 bytes, a uint32. This means we're throwing out the nanoseconds when generating the timestamps. Is there a particular reason for this? This breaks ordering for me where items are made within the same second.

**Comment by achille-roussel** [comment]
This is by design, KSUIDs are not meant to provide absolute ordering. Computer clocks cannot be synchronized accurately enough to provide these guarantee, so KSUID only offers rough ordering by their 4-byte prefix.

This property is often useful to narrow down the search space by performing prefix based matching, but if more precise ordering guarantees are needed the application needs to build this into its logic.
